# Generated by Django 2.0.2 on 2018-03-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0002_contact_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
